### ISSUE TITLE
Support Inserting Chapters

### ISSUE THREAD

**Issue by darkfrog26** [MetaStack-pl/MetaDocs#18]
Currently the chapters are organized starting with "ch00" and incrementing up. What if I want to inject a new chapter in the middle?  This means I have to go through and rename every following chapter file name.

**Comment by tindzk** [comment]
MetaDocs just takes a list of file paths. In ScalaRelational's manual I just iterate over all files in `chapters/` and sort them by their names (see [Main.scala](https://github.com/tindzk/scalarelational-manual/blob/master/src/main/scala/Main.scala#L17)). You could maintain a manual list of file paths instead.
